# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Karlsen/Sep-repository-2/Proyecto_Base_Booster/HW_Base_Booster_2025/Proyecto_Base_Booster_2025.srcs/sources_1/bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2.xci
# IP: The module: 'DEMO_rst_clk_125M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Karlsen/Sep-repository-2/Proyecto_Base_Booster/HW_Base_Booster_2025/Proyecto_Base_Booster_2025.srcs/sources_1/bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_rst_clk_125M_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Karlsen/Sep-repository-2/Proyecto_Base_Booster/HW_Base_Booster_2025/Proyecto_Base_Booster_2025.srcs/sources_1/bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_rst_clk_125M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Karlsen/Sep-repository-2/Proyecto_Base_Booster/HW_Base_Booster_2025/Proyecto_Base_Booster_2025.srcs/sources_1/bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_rst_clk_125M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Karlsen/Sep-repository-2/Proyecto_Base_Booster/HW_Base_Booster_2025/Proyecto_Base_Booster_2025.srcs/sources_1/bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2.xci
# IP: The module: 'DEMO_rst_clk_125M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Karlsen/Sep-repository-2/Proyecto_Base_Booster/HW_Base_Booster_2025/Proyecto_Base_Booster_2025.srcs/sources_1/bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_rst_clk_125M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Karlsen/Sep-repository-2/Proyecto_Base_Booster/HW_Base_Booster_2025/Proyecto_Base_Booster_2025.srcs/sources_1/bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_rst_clk_125M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Karlsen/Sep-repository-2/Proyecto_Base_Booster/HW_Base_Booster_2025/Proyecto_Base_Booster_2025.srcs/sources_1/bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_rst_clk_125M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
