# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Karlsen/Downloads/Zybo-Z7-Master.xdc

# Block Designs: bd/DEMO/DEMO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO || ORIG_REF_NAME==DEMO} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_quad_spi_0_0/DEMO_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_0_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_processing_system7_0_0/DEMO_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_processing_system7_0_0 || ORIG_REF_NAME==DEMO_processing_system7_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_gpio_0_0/DEMO_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_gpio_0_0 || ORIG_REF_NAME==DEMO_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_xbar_0/DEMO_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_xbar_0 || ORIG_REF_NAME==DEMO_xbar_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_ps7_0_axi_periph_0/DEMO_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_ps7_0_axi_periph_0 || ORIG_REF_NAME==DEMO_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_rst_ps7_0_50M_0/DEMO_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_rst_ps7_0_50M_0 || ORIG_REF_NAME==DEMO_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_quad_spi_1_0/DEMO_axi_quad_spi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_quad_spi_1_0 || ORIG_REF_NAME==DEMO_axi_quad_spi_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_iic_0_1 || ORIG_REF_NAME==DEMO_axi_iic_0_1} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_BUZZER_0_0/DEMO_BUZZER_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_BUZZER_0_0 || ORIG_REF_NAME==DEMO_BUZZER_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_traffic_gen_0_0/DEMO_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_traffic_gen_0_0 || ORIG_REF_NAME==DEMO_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_traffic_gen_1_0/DEMO_axi_traffic_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_traffic_gen_1_0 || ORIG_REF_NAME==DEMO_axi_traffic_gen_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_vio_0_0/DEMO_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_vio_0_0 || ORIG_REF_NAME==DEMO_vio_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_rgb_rainbow_0_3/DEMO_rgb_rainbow_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_rgb_rainbow_0_3 || ORIG_REF_NAME==DEMO_rgb_rainbow_0_3} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_smc_4/DEMO_axi_smc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_smc_4 || ORIG_REF_NAME==DEMO_axi_smc_4} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_rst_clk_125M_2/DEMO_rst_clk_125M_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_rst_clk_125M_2 || ORIG_REF_NAME==DEMO_rst_clk_125M_2} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_axi_smc_1_3/DEMO_axi_smc_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_axi_smc_1_3 || ORIG_REF_NAME==DEMO_axi_smc_1_3} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_rgb_controller_0_0/DEMO_rgb_controller_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_rgb_controller_0_0 || ORIG_REF_NAME==DEMO_rgb_controller_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_state_machine_0_0/DEMO_state_machine_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_state_machine_0_0 || ORIG_REF_NAME==DEMO_state_machine_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_vio_1_0/DEMO_vio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_vio_1_0 || ORIG_REF_NAME==DEMO_vio_1_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_vio_2_0/DEMO_vio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_vio_2_0 || ORIG_REF_NAME==DEMO_vio_2_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_ila_0_0/DEMO_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_ila_0_0 || ORIG_REF_NAME==DEMO_ila_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_debouncer_0_0/DEMO_debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_debouncer_0_0 || ORIG_REF_NAME==DEMO_debouncer_0_0} -quiet] -quiet

# IP: bd/DEMO/ip/DEMO_auto_pc_0/DEMO_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DEMO_auto_pc_0 || ORIG_REF_NAME==DEMO_auto_pc_0} -quiet] -quiet

# XDC: bd/DEMO/DEMO_ooc.xdc
